const GET_HUMAN_REQUEST = "GET_HUMAN_REQUEST"
const GET_HUMAN_SUCCESS = "GET_HUMAN_SUCCESS"
const GET_HUMAN_FAILURE = "GET_HUMAN_FAILURE"
const ADD_HUMAN_REQUEST = "ADD_HUMAN_REQUEST"
const ADD_HUMAN_SUCCESS = "ADD_HUMAN_SUCCESS"
const ADD_HUMAN_FAILURE = "ADD_HUMAN_FAILURE"
const EDIT_HUMAN_REQUEST = "EDIT_HUMAN_REQUEST"
const EDIT_HUMAN_SUCCESS = "EDIT_HUMAN_SUCCESS"
const EDIT_HUMAN_FAILURE = "EDIT_HUMAN_FAILURE"
const DELETE_HUMAN_REQUEST = "DELETE_HUMAN_REQUEST"
const DELETE_HUMAN_SUCCESS = "DELETE_HUMAN_SUCCESS"
const DELETE_HUMAN_FAILURE = "DELETE_HUMAN_FAILURE"
const CHOOSE_HUMAN = "CHOOSE_HUMAN"
const SELECTED_MEAL = "SELECTED_MEAL"
const SELECTED_RESTAURANT = "SELECTED_RESTAURANT"
const SELECTED_DISHES = "SELECTED_DISHES"
const SHOW_ERROR_DIALOG = "SHOW_ERROR_DIALOG"
const HIDE_ERROR_DIALOG = "HIDE_ERROR_DIALOG"
const SHOW_NEXT_STEP = "SHOW_NEXT_STEP"
const SHOW_PREVIOUS_STEP = "SHOW_PREVIOUS_STEP"
const SHOW_LAST_STEP = "SHOW_LAST_STEP"
const SEARCH_HUMAN_REQUEST = "SEARCH_HUMAN_REQUEST"
const SEARCH_HUMAN_SUCCESS = "SEARCH_HUMAN_SUCCESS"
const SEARCH_HUMAN_FAILURE = "SEARCH_HUMAN_FAILURE"
export {
    GET_HUMAN_REQUEST,
    GET_HUMAN_SUCCESS,
    GET_HUMAN_FAILURE,
    ADD_HUMAN_REQUEST,
    ADD_HUMAN_SUCCESS,
    ADD_HUMAN_FAILURE,
    EDIT_HUMAN_REQUEST,
    EDIT_HUMAN_SUCCESS,
    EDIT_HUMAN_FAILURE,
    DELETE_HUMAN_REQUEST,
    DELETE_HUMAN_SUCCESS,
    DELETE_HUMAN_FAILURE,
    CHOOSE_HUMAN,
    SELECTED_MEAL,
    SELECTED_RESTAURANT,
    SELECTED_DISHES,
    SHOW_ERROR_DIALOG,
    HIDE_ERROR_DIALOG,
    SHOW_NEXT_STEP,
    SHOW_PREVIOUS_STEP,
    SHOW_LAST_STEP,
    SEARCH_HUMAN_REQUEST,
    SEARCH_HUMAN_SUCCESS,
    SEARCH_HUMAN_FAILURE
}
